DROP TABLE IF EXISTS dogs, heroes;
CREATE TABLE dogs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  weight TEXT
);
CREATE TABLE heroes (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  species TEXT,
  ability TEXT
);